;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-append-line
	evil-backward-word-begin
	evil-forward-WORD-begin
	evil-forward-char
	evil-forward-word-begin
	evil-forward-word-end
	evil-insert
	evil-normal-state
	))

(setq mc/cmds-to-run-once
      '(
	evil-mouse-drag-region
	keyboard-escape-quit
	mouse-set-region
	))
