* Emacs Configuration
  
  This document is an overview of my emacs configuration with notes explaining the why and how of each bit of code works. This document can be cloned in along with this repo if you would like to emulate my emacs config.

  I would however recomend you arive 

** Overview and References

*** How it works

    The intent of this file is to use org-babel to have org mode generate my init.el and other files as needed while providing documentation in place.
    See: https://orgmode.org/worg/org-contrib/babel/index.html

    Code can be embedded using code blocks with both syntax highlighting and export instructions this code below for example will set the python mode interpreter to python3 not the default python.

    #+begin_src emacs-lisp
      ;; example
    #+end_src
    
*** Conventions

    For this document configuration changes will be seperated into related groups for ease of understanding for example all items related to python could be together as will all org mode items. 

*** References and Good Information

    For my emacs adventure I am following along with one major source of information which is the emacs from scratch series by "system crafters". You can find these here.

    https://www.youtube.com/watch?v=74zOY-vgkyw&list=PLEoMzSkcN8oPH1au7H6B7bBJ4ZO7BXjSZ&t=0s

    There are tons of snippets in my code which are borrowed from this series and if you are looking for a good tour of emacs features this is great. I also am following along with these books.

    https://www.oreilly.com/library/view/gnu-emacs-pocket/1565924967/

    and

    https://masteringemacs.org/book

    I am a professional software engineer but I am mainly looking at emacs for its documentation and org mode. If I can fit it in with my professional activities (python, sql, plsql) even better.

** Configuration

*** Use Package

    Since we will use use-package to easily include and require packages lets get use-package very first. We also will point packages to elpa and melpa.

    #+begin_src emacs-lisp
      ;; Initialize package sources
      (require 'package)

      (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                               ("org" . "https://orgmode.org/elpa/")
                               ("elpa" . "https://elpa.gnu.org/packages/")
                               ("tromey" . "https://tromey.com/elpa/")
                               ("melpa-stable" . "https://stable.melpa.org/packages/")
                               ))

      (add-to-list 'package-pinned-packages '(cider . "melpa-stable") t)
      (add-to-list 'package-pinned-packages '(magit . "melpa-stable") t)

      (package-initialize)
      (unless package-archive-contents
        (package-refresh-contents))

      ;; Initialize use-package on non-Linux platforms
      (unless (package-installed-p 'use-package)
        (package-install 'use-package))

      (unless (package-installed-p 'multtiple-cursors)
        (package-install 'multiple-cursors))

      (require 'use-package)
      (setq use-package-always-ensure t)

      ;; uncomment this as needed or run manually
      ;;(package-refresh-contents ) ;; also update from melpa etc

      #+end_src

*** Basic Settings

    We will turn off a number of things to make the window smaller. These settings just remove much of the window padding as well as memu bars. We will also turn the bell of and make it visible flash on the screen instead.

    The very last bit is to default our backups to a special folder. Emacs keeps temp files and if you do not do this you'll end up with ~ named files in every directory. Alternatively you can turn these backups off BUT its a great feature.

    #+begin_src emacs-lisp
      ;; some basics
      (scroll-bar-mode -1)          ; Disable visible scrollbar
      (tool-bar-mode -1)            ; Disable the toolbar
      (tooltip-mode -1)             ; Disable tooltips
      (set-fringe-mode 10)          ; Give some breathing room

      ;; Set up the visible bell
      ;; (setq visible-bell t) ;; linux windows
      ;; (setq visible-bell nil)
      (setq ring-bell-function (lambda ()  ;; macos
				 (invert-face 'mode-line)
				 (run-with-timer 0.1 nil 'invert-face 'mode-line)))

      ;; send backsups to one specific directory
      (setq backup-directory-alist '(("." . "~/Organization/EmacsBackups")))
    #+end_src

*** Powershell Windows Only

    Please note to run this on windows machines manually for now 

    M-x package-install RET powershell RET

    to get powershell working then you simply run M-x powershell 

    see https://www.reddit.com/r/emacs/comments/op8ue1/how_set_powershell_as_the_default_shell_which_mx/

    or https://docs.microsoft.com/en-us/archive/blogs/dotnetinterop/run-powershell-as-a-shell-within-emacs

    
    #+begin_src emacs-lisp

    (if
    (eq system-type 'windows-nt) 
      (progn
       (prefer-coding-system 'utf-8)
       (setq explicit-shell-file-name
        "C:/Users/csusggsn/AppData/Local/Programs/Git/bin/bash.exe")
       (setq shell-file-name explicit-shell-file-name)
       (add-to-list 'exec-path 
        "C:/Users/csusggsn/AppData/Local/Programs/Git/bin/bash.exe")
      ) 
    )

    #+end_src

*** Org Mode Changes
    
    Various configs for org mode

    #+begin_src emacs-lisp
      (defun old_greg/org-mode-setup ()
        (org-indent-mode)
        (variable-pitch-mode 0)
        (visual-line-mode 1))

      ;; Org Mode Configuration ------------------------------------------------------

      (defun old_greg/org-font-setup ()
        ;; Replace list hyphen with dot
        (font-lock-add-keywords 'org-mode
                                '(("^ *\\([-]\\) "
                                   (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•")))))))

      ;; Set faces for heading levels
      (dolist (face '((org-level-1 . 1.2)
                      (org-level-2 . 1.1)
                      (org-level-3 . 1.05)
                      (org-level-4 . 1.0)
                      (org-level-5 . 1.1)
                      (org-level-6 . 1.1)
                      (org-level-7 . 1.1)
                      (org-level-8 . 1.1)))
        )

      (use-package org
        :hook (org-mode . old_greg/org-mode-setup)
        :config
        (setq org-ellipsis " ▾")

        (setq org-agenda-start-with-log-mode t)
        (setq org-log-done 'time)
        (setq org-log-into-drawer t)

        (custom-set-faces
         '(org-block-begin-line ((t (:background "#bd93f9" :foreground "#f8f8f2"))))
         '(org-block-end-line   ((t (:background "#bd93f9" :foreground "#f8f8f2")))))
        (require 'org-habit)
        (add-to-list 'org-modules 'org-habit)
        (setq org-habit-graph-column 60)

        (setq org-todo-keywords
              '((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d!)")
                (sequence "BACKLOG(b)" "PLAN(p)" "READY(r)" "ACTIVE(a)" "REVIEW(v)" "WAIT(w@/!)" "HOLD(h)" "|" "COMPLETED(c)" "CANC(k@)")))

        (setq org-refile-targets
              '(("~/Organization/archive.org" :maxlevel . 1)
                ("~/Organization/todo.org" :maxlevel . 1)))

        ;; Save Org buffers after refiling!
        (advice-add 'org-refile :after 'org-save-all-org-buffers)

        (setq org-tag-alist
              '((:startgroup)
                                              ; Put mutually exclusive tags here
                (:endgroup)
                ("@errand" . ?E)
                ("@home" . ?H)
                ("@work" . ?W)
                ("agenda" . ?a)
                ("planning" . ?p)
                ("publish" . ?P)
                ("batch" . ?b)
                ("note" . ?n)
                ("idea" . ?i)
                ("Database Core" . ?c)
                ("Database Web" . ?w)
                ("Datavault" . ?v)
                ("Misc Creditsafe" . ?m)

                ))

        ;; Configure custom agenda views
        (setq org-agenda-custom-commands
              '(("d" "Dashboard"
                 ((agenda "" ((org-deadline-warning-days 7)))
                  (todo "NEXT"
                        ((org-agenda-overriding-header "Next Tasks")))
                  (tags-todo "agenda/ACTIVE" ((org-agenda-overriding-header "Active Projects")))))

                ("n" "Next Tasks"
                 ((todo "NEXT"
                        ((org-agenda-overriding-header "Next Tasks")))))

                ("W" "Work Tasks" tags-todo "+work-email")

                ;; Low-effort next actions
                ("e" tags-todo "+TODO=\"NEXT\"+Effort<15&+Effort>0"
                 ((org-agenda-overriding-header "Low Effort Tasks")
                  (org-agenda-max-todos 20)
                  (org-agenda-files org-agenda-files)))

                ("w" "Workflow Status"
                 ((todo "WAIT"
                        ((org-agenda-overriding-header "Waiting on External")
                         (org-agenda-files org-agenda-files)))
                  (todo "REVIEW"
                        ((org-agenda-overriding-header "In Review")
                         (org-agenda-files org-agenda-files)))
                  (todo "PLAN"
                        ((org-agenda-overriding-header "In Planning")
                         (org-agenda-todo-list-sublevels nil)
                         (org-agenda-files org-agenda-files)))
                  (todo "BACKLOG"
                        ((org-agenda-overriding-header "Project Backlog")
                         (org-agenda-todo-list-sublevels nil)
                         (org-agenda-files org-agenda-files)))
                  (todo "READY"
                        ((org-agenda-overriding-header "Ready for Work")
                         (org-agenda-files org-agenda-files)))
                  (todo "ACTIVE"
                        ((org-agenda-overriding-header "Active Projects")
                         (org-agenda-files org-agenda-files)))
                  (todo "COMPLETED"
                        ((org-agenda-overriding-header "Completed Projects")
                         (org-agenda-files org-agenda-files)))
                  (todo "CANC"
                        ((org-agenda-overriding-header "Cancelled Projects")
                         (org-agenda-files org-agenda-files)))))))

        (setq org-capture-templates
              `(("t" "Tasks / Projects")
                ("tt" "Task" entry (file+olp "~/Projects/Code/emacs-from-scratch/OrgFiles/Tasks.org" "Inbox")
                 "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)

                ("j" "Journal Entries")
                ("jj" "Journal" entry
                 (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
                 "\n* %<%I:%M %p> - Journal :journal:\n\n%?\n\n"
                 ;; ,(dw/read-file-as-string "~/Notes/Templates/Daily.org")
                 :clock-in :clock-resume
                 :empty-lines 1)
                ("jm" "Meeting" entry
                 (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
                 "* %<%I:%M %p> - %a :meetings:\n\n%?\n\n"
                 :clock-in :clock-resume
                 :empty-lines 1)

                ("w" "Workflows")
                ("we" "Checking Email" entry (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
                 "* Checking Email :email:\n\n%?" :clock-in :clock-resume :empty-lines 1)

                ("m" "Metrics Capture")
                ("mw" "Weight" table-line (file+headline "~/Projects/Code/emacs-from-scratch/OrgFiles/Metrics.org" "Weight")
                 "| %U | %^{Weight} | %^{Notes} |" :kill-buffer t)))

        (define-key global-map (kbd "C-c j")
          (lambda () (interactive) (org-capture nil "jj")))

        (old_greg/org-font-setup))

      (defun old_greg/org-mode-visual-fill ()
        (setq visual-fill-column-width 145
              visual-fill-column-center-text t)
        (visual-fill-column-mode 1))

      (use-package visual-fill-column
        :hook (org-mode . old_greg/org-mode-visual-fill))

      (if
          (eq system-type 'windows-nt) 
          (setq org-agenda-files '("C:\\Organization\\Users\\csusggsn\\todo.org"))

        )

      (if
          (eq system-type 'darwin) 
          (setq org-agenda-files '("~/Organization/todo.org"))

        )

      (global-set-key (kbd "C-c a") 'org-agenda)
    #+end_src

*** Magit and Projectile

    These applications are just to allow for git and project management. Copied from system crafters

    #+begin_src emacs-lisp

      (use-package projectile
        :diminish projectile-mode
        :config (projectile-mode)
        :custom ((projectile-completion-system 'ivy))
        :bind-keymap
        ("C-c p" . projectile-command-map)
        :init
        ;; NOTE: Set this to the folder where you keep your Git repos!
        (when (file-directory-p "~/Projects/Code")
          (setq projectile-project-search-path '("~/Projects/Code")))
        (setq projectile-switch-project-action #'projectile-dired))

      (use-package counsel-projectile
        :config (counsel-projectile-mode))

      (use-package magit
        :bind (("C-x g" . magit-status)
               ("C-x C-g" . magit-status))
        :custom
        (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

    #+end_src

*** SQL and Oracle

    #+begin_src emacs-lisp
     (add-to-list 'load-path "~/.emacs.d/customizations")
     (load "sqlplus.el")
     (load "plsql.el")

    #+end_src

*** Clojure

    I will be spending time this year learning clojure and making a terminal app in it here are some ext for it

    Much of this configuration is just lifted from the brave clojure book see

    https://github.com/flyingmachine/emacs-for-clojure/

    Rather than just using their code however I've added it into my own init.el.

    Note I have cloned their customizations directory.


    #+begin_src emacs-lisp

      ;; The packages you want installed. You can also install these
      ;; manually with M-x package-install
      ;; Add in your own as you wish:
      (defvar my-packages
        '(;; makes handling lisp expressions much, much easier
          ;; Cheatsheet: http://www.emacswiki.org/emacs/PareditCheatsheet
          paredit

          ;; key bindings and code colorization for Clojure
          ;; https://github.com/clojure-emacs/clojure-mode
          clojure-mode

          ;; extra syntax highlighting for clojure
          clojure-mode-extra-font-locking

          ;; integration with a Clojure REPL
          ;; https://github.com/clojure-emacs/cider
          cider

          ;; allow ido usage in as many contexts as possible. see
          ;; customizations/navigation.el line 23 for a description
          ;; of ido
          ido-completing-read+

          ;; Enhances M-x to allow easier execution of commands. Provides
          ;; a filterable list of possible commands in the minibuffer
          ;; http://www.emacswiki.org/emacs/Smex
          smex

          ;; project navigation
          ;;projectile

          ;; colorful parenthesis matching
          rainbow-delimiters

          ;; edit html tags like sexps
          tagedit

          ;; git integration
          ;;magit
          ))

      ;; On OS X, an Emacs instance started from the graphical user
      ;; interface will have a different environment than a shell in a
      ;; terminal window, because OS X does not run a shell during the
      ;; login. Obviously this will lead to unexpected results when
      ;; calling external utilities like make from Emacs.
      ;; This library works around this problem by copying important
      ;; environment variables from the user's shell.
      ;; https://github.com/purcell/exec-path-from-shell
      (if (eq system-type 'darwin)
          (add-to-list 'my-packages 'exec-path-from-shell))

      (dolist (p my-packages)
        (when (not (package-installed-p p))
          (package-install p)))


      (add-to-list 'load-path "~/.emacs.d/vendor")


      ;;;;
      ;; Customization
      ;;;;

      ;; Add a directory to our load path so that when you `load` things
      ;; below, Emacs knows where to look for the corresponding file.
      ;; (add-to-list 'load-path "~/.emacs.d/customizations")

      ;; Sets up exec-path-from-shell so that Emacs will use the correct
      ;; environment variables
      (load "shell-integration.el")
      (load "dired+.el")

      ;; These customizations make it easier for you to navigate files,
      ;; switch buffers, and choose options from the minibuffer.
      (load "navigation.el")

      ;; These customizations change the way emacs looks and disable/enable
      ;; some user interface elements
      (load "ui.el")

      ;; These customizations make editing a bit nicer.
      (load "editing.el")

      ;; Hard-to-categorize customizations
      (load "misc.el")

      ;; For editing lisps
      (load "elisp-editing.el")

      ;; Langauage-specific
      (load "setup-clojure.el")
      (load "setup-js.el")
      (custom-set-variables
       ;; custom-set-variables was added by Custom.
       ;; If you edit it by hand, you could mess it up, so be careful.
       ;; Your init file should contain only one such instance.
       ;; If there is more than one, they won't work right.
       '(coffee-tab-width 2)
       '(package-selected-packages
         (quote
          (magit tagedit rainbow-delimiters projectile smex ido-completing-read+ cider clojure-mode-extra-font-locking clojure-mode paredit exec-path-from-shell))))
      (custom-set-faces
       ;; custom-set-faces was added by Custom.
       ;; If you edit it by hand, you could mess it up, so be careful.
       ;; Your init file should contain only one such instance.
       ;; If there is more than one, they won't work right.
       )
    #+end_src

*** Keyboard Changes

    Any simple keymap changes are here there can be more specific key binds per package which will be stored with their associated package.

    #+begin_src emacs-lisp
      (global-set-key (kbd "<escape>") 'keyboard-escape-quit) ;; Make ESC quit prompts

      (use-package general
	:after evil
	:config
	(general-create-definer old_greg/leader-keys
				:keymaps '(normal insert visual emacs)
				:prefix "SPC"
				:global-prefix "C-SPC")

	(old_greg/leader-keys
	 "t"  '(:ignore t :which-key "toggles")
	 "tt" '(counsel-load-theme :which-key "choose theme")
	 "fde" '(lambda () (interactive) (find-file (expand-file-name "~/.emacs.d/Emacs.org")))))

      (use-package evil
	:init
	(setq evil-want-integration t)
	(setq evil-want-keybinding nil)
	(setq evil-want-C-u-scroll t)
	(setq evil-want-C-i-jump nil)
	:config
	(evil-mode 1)
	(define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
	(define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)


	;; Use visual line motions even outside of visual-line-mode buffers
	(evil-global-set-key 'motion "j" 'evil-next-visual-line)
	(evil-global-set-key 'motion "k" 'evil-previous-visual-line)

	(evil-set-initial-state 'messages-buffer-mode 'normal)
	(evil-set-initial-state 'dashboard-mode 'normal)
        (evil-set-initial-state 'ibuffer-mode 'normal)
        (evil-set-initial-state 'bookmark-bmenu-mode 'normal)
        (evil-set-initial-state 'dired-mode 'emacs)
        (evil-set-initial-state 'sunrise-mode 'emacs))

      (use-package evil-collection
	:after evil
	:config
	(evil-collection-init))


    #+end_src

*** Cursors

    I am using the multiple cursor package. In emacs 28 I believe I can remove this but for now

    https://github.com/magnars/multiple-cursors.el
    
    M-x package-install multiple-cursors

    #+begin_src emacs-lisp
      (require 'multiple-cursors)
      (global-set-key (kbd "C-S-c C-S-c") 'mc/edit-lines)
      (global-set-key (kbd "C->") 'mc/mark-next-like-this)
      (global-set-key (kbd "C-<") 'mc/mark-previous-like-this)
      (global-set-key (kbd "C-c C-<") 'mc/mark-all-like-this)
    #+end_src 

*** Appearance

    I am using doom emacs bar as well as a theme from there for basic appearnance as well as some specific fonts. Please ensure you have IBM Plex Mono fonts installed if you want to use this.

    Please note I have some lines here commented in and out to account for different machines. I use emacs mostly in a Debian VM but I also use it on Macos and Windows natively for work. Font height and $PATH work different for macs.

    For all the icons fonts on windows you will need to "install" them. To do this follow the details 

    https://github.com/hlissner/doom-emacs/issues/2575

    The powershell commands are
     cd $tempFonts
     $destination = (New-Object -ComObject Shell.Application).Namespace(0x14)
     ls *.ttf | % { $destination.CopyHere($_.FullName, 0x10) }     
    

    #+begin_src emacs-lisp
	    (global-hl-line-mode 1)       ; HL Lines globally on
	    (set-face-background hl-line-face "gray23")
	    ;; hidpi
	    ;;(set-face-attribute 'default nil :font "IBM Plex Mono" :height 170)
	    ;; normal screens
	    (set-face-attribute 'default nil :font "IBM Plex Mono" :height 135)

	    (use-package doom-modeline
	      :ensure t
	      :init (doom-modeline-mode 1)
	      :custom ((doom-modeline-height 13)))

	    ;; NOTE: The first time you load your configuration on a new machine, you'll
	    ;; need to run the following command interactively so that mode line icons
	    ;; display correctly:
	    ;;
	    ;; M-x all-the-icons-install-fonts
	    ;; icons 
	    (use-package all-the-icons)

	    (use-package doom-themes
	      :init (load-theme 'doom-dracula t))

	    (use-package rainbow-delimiters
	      :hook (prog-mode . rainbow-delimiters-mode))

      (setq doom-modeline-modal-icon nil)

    #+end_src

**** Line Numbers

     We turn on line numbers but turn them off in various modes like terminal and dired.

    #+begin_src emacs-lisp
            (column-number-mode)
            (setq display-line-numbers-type 'relative)
            (global-display-line-numbers-mode t)

            ;; Disable line numbers for some modes
            (dolist (mode '(term-mode-hook
                            dired-mode-hook
                            shell-mode-hook
                            org-mode-hook
                            eshell-mode-hook))
              (add-hook mode (lambda () (display-line-numbers-mode 0))))
    #+end_src

*** Enviornment Variables

    In this section I am including some enviornment variables that sometimes are not loaded. For example on a mac if you launch emacs from spotlight it will not inherit your enviornment variables from your .zshrc or .bash_profile.

    This will ensure some things are present for me. In my case I'm ensuring paths for Oracle SQL Plus and TNS files are picked up as well as the python I prefer

    This is wrapped in a mac conditional this is not needed on my windows enviornment.

    Frankly homebrew and macs are a mess

    #+begin_src emacs-lisp
      (when (memq window-system '(mac ns x))
	   (setenv "PATH" (concat "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:" (getenv "PATH"))) ;; gets my homebrew installed python
	   (setenv "PATH" (concat "/Users/gregsilverstein/Oracle/instantclient:" (getenv "PATH"))) ;; gets sqlplus and oracle directory in
	   (setenv "PATH" (concat "/opt/homebrew/opt/openjdk:" (getenv "PATH"))) ;; stuff for java
	   (setenv "PATH" (concat "/opt/homebrew/opt/openjdk/include:" (getenv "PATH"))) ;; stuff for java
	   (setenv "PATH" (concat "/opt/homebrew/opt/openjdk/bin:" (getenv "PATH"))) ;; stuff for java
	   (setenv "ORACLE_HOME"  "/Users/gregsilverstein/Oracle/instantclient") ;; oracle stuff
	   (setenv "DYLD_LIBRARY_PATH"  "/Users/gregsilverstein/Oracle/instantclient") ;; oracle stuff
	   (setenv "OCI_LIB_DIR"  "/Users/gregsilverstein/Oracle/instantclient") ;; oracle stuff
	   (setenv "OCI_INC_DIR"  "/Users/gregsilverstein/Oracle/instantclient/sdk/include") ;; oracle stuff
	   (setenv "TNS_ADMIN"  "/Users/gregsilverstein/Oracle/network/wallet") ;; oracle stuff
	   )
    #+end_src

*** Python

    Here we set the python to python 3. My Mac has both python 2 and python 3 installed so this keeps it on the right one.

    
    #+begin_src emacs-lisp
      ;; python3 
      (setq python-shell-interpreter "python3")
    #+end_src

*** Mac Specific

    Here we use a package to force emacs to use the bash path on macos.

    #+begin_src emacs-lisp
      (use-package exec-path-from-shell)
      (when (memq window-system '(mac ns x))
	(exec-path-from-shell-initialize))
      (use-package command-log-mode)
    #+end_src

*** Exploration Aids

    These packages Ivy Which Key and Helpful provide aid to the user in using emacs.

    Ivy has some usefull key shortcuts that are better than default.
    Which Key will show a context menu as you hit a key sequence. For example if you hit C-C you will then see all of the org mode options.
    Helpful is simply better help. It gives you hints on all sorts of menus.

    #+begin_src emacs-lisp

      (use-package ivy
	:diminish
	:bind (("C-s" . swiper)
	       :map ivy-minibuffer-map
	       ("TAB" . ivy-alt-done)
	       ("C-l" . ivy-alt-done)
	       ("C-j" . ivy-next-line)
	       ("C-k" . ivy-previous-line)
	       :map ivy-switch-buffer-map
	       ("C-k" . ivy-previous-line)
	       ("C-l" . ivy-done)
	       ("C-d" . ivy-switch-buffer-kill)
	       :map ivy-reverse-i-search-map
	       ("C-k" . ivy-previous-line)
	       ("C-d" . ivy-reverse-i-search-kill))
	:config
	(ivy-mode 1))

      (use-package which-key
	:init (which-key-mode)
	:diminish which-key-mode
	:config

	(setq which-key-idle-delay 1))

      (use-package ivy-rich
	:init
	(ivy-rich-mode 1))

      (use-package counsel
	:bind (("C-M-j" . 'counsel-switch-buffer)
	       :map minibuffer-local-map
	       ("C-r" . 'counsel-minibuffer-history))
	:custom
	(counsel-linux-app-format-function #'counsel-linux-app-format-function-name-only)
	:config
	(counsel-mode 1))

      (use-package helpful
	:custom
	(counsel-describe-function-function #'helpful-callable)
	(counsel-describe-variable-function #'helpful-variable)
	:bind
	([remap describe-function] . counsel-describe-function)
	([remap describe-command] . helpful-command)
	([remap describe-variable] . counsel-describe-variable)
	([remap describe-key] . helpful-key))
    #+end_src

*** Everything Else

    Anything else random will be here. Right now this is just the git client which I have not configured fully for myself. This is sort of a "work in progress area" of my config.
    
    
#+begin_src emacs-lisp
  (custom-set-variables
   ;; custom-set-variables was added by Custom.
   ;; If you edit it by hand, you could mess it up, so be careful.
   ;; Your init file should contain only one such instance.
   ;; If there is more than one, they won't work right.
   '(package-selected-packages
     '(magit helpful counsel ivy-rich which-key rainbow-delimiters doom-themes doom-modeline ivy command-log-mode use-package)))
  (custom-set-faces
   ;; custom-set-faces was added by Custom.
   ;; If you edit it by hand, you could mess it up, so be careful.
   ;; Your init file should contain only one such instance.
   ;; If there is more than one, they won't work right.
   )
#+end_src
