* Emacs Configuration
  
  This document is an overview of my emacs configuration with notes explaining the why and how of each bit of code works. This document can be cloned in along with this repo if you would like to emulate my emacs config.

  I would however recomend you arive 

** Overview and References

*** How it works

    The intent of this file is to use org-babel to have org mode generate my init.el and other files as needed while providing documentation in place.
    See: https://orgmode.org/worg/org-contrib/babel/index.html

    Code can be embedded using code blocks with both syntax highlighting and export instructions this code below for example will set the python mode interpreter to python3 not the default python.

    #+begin_src emacs-lisp
      ;; example
    #+end_src
    
*** Conventions

    For this document configuration changes will be seperated into related groups for ease of understanding for example all items related to python could be together as will all org mode items. 

*** References and Good Information

    For my emacs adventure I am following along with one major source of information which is the emacs from scratch series by "system crafters". You can find these here.

    https://www.youtube.com/watch?v=74zOY-vgkyw&list=PLEoMzSkcN8oPH1au7H6B7bBJ4ZO7BXjSZ&t=0s

    There are tons of snippets in my code which are borrowed from this series and if you are looking for a good tour of emacs features this is great. I also am following along with these books.

    https://www.oreilly.com/library/view/gnu-emacs-pocket/1565924967/

    and

    https://masteringemacs.org/book

    I am a professional software engineer but I am mainly looking at emacs for its documentation and org mode. If I can fit it in with my professional activities (python, sql, plsql) even better.

** Configuration

*** Use Package

    Since we will use use-package to easily include and require packages lets get use-package very first. We also will point packages to elpa and melpa.

    #+begin_src emacs-lisp
      ;; Initialize package sources
      (require 'package)

      (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                               ("org" . "https://orgmode.org/elpa/")
                               ("elpa" . "https://elpa.gnu.org/packages/")
                               ("tromey" . "https://tromey.com/elpa/")
                               ("melpa-stable" . "https://stable.melpa.org/packages/")
                               ))

      (add-to-list 'package-pinned-packages '(cider . "melpa-stable") t)
      (add-to-list 'package-pinned-packages '(magit . "melpa-stable") t)

      (package-initialize)
      (unless package-archive-contents
        (package-refresh-contents))

      ;; Initialize use-package on non-Linux platforms
      (unless (package-installed-p 'use-package)
        (package-install 'use-package))

      (unless (package-installed-p 'multtiple-cursors)
        (package-install 'multiple-cursors))

      (require 'use-package)
      (setq use-package-always-ensure t)

      ;; uncomment this as needed or run manually
      ;;(package-refresh-contents ) ;; also update from melpa etc

      #+end_src

*** Enviornment Variables

    In this section I am including some enviornment variables that sometimes are not loaded. For example on a mac if you launch emacs from spotlight it will not inherit your enviornment variables from your .zshrc or .bash_profile.

    This will ensure some things are present for me. In my case I'm ensuring paths for Oracle SQL Plus and TNS files are picked up as well as the python I prefer

    This is wrapped in a mac conditional this is not needed on my windows enviornment.

    Frankly homebrew and macs are a mess

    #+begin_src emacs-lisp
      (when (memq window-system '(mac ns x))
	   (setenv "PATH" (concat "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:" (getenv "PATH"))) ;; gets my homebrew installed python
	   (setenv "PATH" (concat "/Users/gregsilverstein/Oracle/instantclient:" (getenv "PATH"))) ;; gets sqlplus and oracle directory in
	   (setenv "PATH" (concat "/opt/homebrew/opt/openjdk:" (getenv "PATH"))) ;; stuff for java
	   (setenv "PATH" (concat "/opt/homebrew/opt/openjdk/include:" (getenv "PATH"))) ;; stuff for java
	   (setenv "PATH" (concat "/opt/homebrew/opt/openjdk/bin:" (getenv "PATH"))) ;; stuff for java
	   (setenv "ORACLE_HOME"  "/Users/gregsilverstein/Oracle") ;; oracle stuff
	   (setenv "DYLD_LIBRARY_PATH"  "/Users/gregsilverstein/Oracle/instantclient") ;; oracle stuff
	   (setenv "OCI_LIB_DIR"  "/Users/gregsilverstein/Oracle/instantclient") ;; oracle stuff
	   (setenv "OCI_INC_DIR"  "/Users/gregsilverstein/Oracle/instantclient/sdk/include") ;; oracle stuff
	   (setenv "TNS_ADMIN"  "/Users/gregsilverstein/Oracle/network/wallet") ;; oracle stuff
	   )
    #+end_src


*** Basic Settings

    We will turn off a number of things to make the window smaller. These settings just remove much of the window padding as well as memu bars. We will also turn the bell of and make it visible flash on the screen instead.

    The very last bit is to default our backups to a special folder. Emacs keeps temp files and if you do not do this you'll end up with ~ named files in every directory. Alternatively you can turn these backups off BUT its a great feature.

    #+begin_src emacs-lisp
      ;; some basics
      (tool-bar-mode -1)            ; Disable the toolbar
      (set-fringe-mode 10)          ; Give some breathing room
      (server-start)
      (tab-bar-mode)
      (add-to-list 'default-frame-alist '(fullscreen . maximized))
      ;; Set up the visible bell
      ;; (setq visible-bell t) ;; linux windows
      ;; (setq visible-bell nil)
      (setq ring-bell-function (lambda ()  ;; macos
                                 (invert-face 'mode-line)
                                 (run-with-timer 0.1 nil 'invert-face 'mode-line)))

      ;; send backsups to one specific directory
      (setq backup-directory-alist '(("." . "~/Organization/98_Emacs_Backups")))

      (use-package term
        :config
        (setq explicit-shell-file-name "bash") ;; Change this to zsh, etc
        ;;(setq explicit-zsh-args '())         ;; Use 'explicit-<shell>-args for shell-specific args

        ;; Match the default Bash shell prompt.  Update this if you have a custom prompt
        (setq term-prompt-regexp ".*>\s\]"))


      (use-package eterm-256color
        :hook (term-mode . eterm-256color-mode))

      (use-package vterm
        :commands vterm
        :config
        (setq term-prompt-regexp ".*>\s\]")  ;; Set this to match your custom shell prompt
        (setq vterm-max-scrollback 10000))
    #+end_src

*** Powershell Windows Only

    Please note to run this on windows machines manually for now 

    M-x package-install RET powershell RET

    to get powershell working then you simply run M-x powershell 

    see https://www.reddit.com/r/emacs/comments/op8ue1/how_set_powershell_as_the_default_shell_which_mx/

    or https://docs.microsoft.com/en-us/archive/blogs/dotnetinterop/run-powershell-as-a-shell-within-emacs

    in order to make magit work on windows i needed to run
    
    $>  ssh-add C:\Users\csusggsn\.ssh\new_bb
    
    Manually on the command line after adding my git root directory to my path otherwise windows would error on this

    In order for git to use ssh keys properly. This may need to be turned into a init script or something I run on boot

    After rebooting this week i can see that this does need to happen automatically. It seems like magit is using powershell or cmd

    to perform my git pushes. The process is to run

      C:\Windows\System32\OpenSSH>ssh-agent.exe
      C:\Windows\System32\OpenSSH>ssh-add.exe C:\Users\<username>\.ssh\new_bb    

    #+begin_src emacs-lisp

    (if
    (eq system-type 'windows-nt) 
      (progn
       (prefer-coding-system 'utf-8)
       (setq explicit-shell-file-name
        "C:/Users/csusggsn/AppData/Local/Programs/Git/bin/bash.exe")
       (setq shell-file-name explicit-shell-file-name)
       (add-to-list 'exec-path 
        "C:/Users/csusggsn/AppData/Local/Programs/Git/bin/bash.exe")
      ) 
    )

    #+end_src

*** Org Mode Changes
    
    Various configs for org mode

    #+begin_src emacs-lisp
      (defun old_greg/org-mode-setup ()
        ;; (org-indent-mode) ;;Currently debating this bit
        (variable-pitch-mode 0)
        (visual-line-mode 1))

      ;; Org Mode Configuration ------------------------------------------------------

      (defun old_greg/org-font-setup ()
        ;; Replace list hyphen with dot
        (font-lock-add-keywords 'org-mode
                                '(("^ *\\([-]\\) "
                                   (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•")))))))

      ;; Set faces for heading levels
      (dolist (face '((org-level-1 . 1.2)
                      (org-level-2 . 1.1)
                      (org-level-3 . 1.05)
                      (org-level-4 . 1.0)
                      (org-level-5 . 1.1)
                      (org-level-6 . 1.1)
                      (org-level-7 . 1.1)
                      (org-level-8 . 1.1)))
        )

      (use-package org
        :hook (org-mode . old_greg/org-mode-setup)
        :config
        (setq org-ellipsis " ▾")

        (setq org-agenda-start-with-log-mode t)
        (setq org-log-done 'time)
        (setq org-log-into-drawer t)

        (setq org-todo-keywords
              '((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d!)")
                (sequence "BACKLOG(b)" "PLAN(p)" "READY(r)" "ACTIVE(a)" "REVIEW(v)" "WAIT(w@/!)" "HOLD(h)" "|" "COMPLETED(c)" "CANC(k@)")))

        (setq org-tag-alist
              '((:startgroup)
                (:endgroup)
                ("@errand" . ?E)
                ("@home" . ?H)
                ("planning" . ?p)
                ("note" . ?n)
                ("idea" . ?i)
                ("Personal" . ?x)
                ("Misc" . ?X)
                ("@Database Core" . ?C)
                ("@Database Web" . ?W)
                ("@Datavault" . ?D)
                ("@Misc Creditsafe" . ?M)
                ))


        (old_greg/org-font-setup))

      (defun old_greg/org-mode-visual-fill ()
        (setq visual-fill-column-width 200 
              visual-fill-column-center-text t)
        (visual-fill-column-mode 1))

      (use-package visual-fill-column
        :hook (org-mode . old_greg/org-mode-visual-fill))

      (if
          (eq system-type 'windows-nt) 
          (setq org-agenda-files '("C:\\Users\\csusggsn\\Organization\\todo.org"))
        )

      (if
          (eq system-type 'darwin) 
          (setq org-agenda-files '("~/Organization/todo.org"))
        )

      (global-set-key (kbd "C-c a") 'org-agenda)

      (custom-set-faces
       '(org-block-begin-line
         ((t (:background "#212121" :extend t))))
       '(org-block
         ((t (:background "#252525" :extend t))))
       '(org-block-end-line
         ((t (:background "#212121" :extend t))))
       )

      (org-babel-do-load-languages
       'org-babel-load-languages
       '((emacs-lisp . t)
         (python . t)))

      (push '("conf-unix" . conf-unix) org-src-lang-modes)

        #+end_src

*** Magit and Projectile

    These applications are just to allow for git and project management. Copied from system crafters

    #+begin_src emacs-lisp

      (use-package projectile
        :diminish projectile-mode
        :config (projectile-mode)
        :bind-keymap
        ("C-c p" . projectile-command-map)
        :init
        ;; NOTE: Set this to the folder where you keep your Git repos!
        (when (file-directory-p "~/Projects/Code")
          (setq projectile-project-search-path '("~/Projects/Code")))
        (setq projectile-switch-project-action #'projectile-dired))


      (use-package magit
        :bind (("C-x g" . magit-status)
               ("C-x C-g" . magit-status))
        :custom
        (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

    #+end_src

*** SQL and Oracle

    #+begin_src emacs-lisp
      (add-to-list 'load-path "~/.emacs.d/customizations")
      (load "sqlplus.el")
      (load "plsql.el")

      (require 'sqlplus)
      (add-to-list 'auto-mode-alist '("\\.sqp\\'" . sqlplus-mode))

      ;;  If you want PL/SQL support also, try something like this:
      ;;
      (require 'plsql)
      (setq auto-mode-alist
            (append '(("\\.pls\\'" . plsql-mode) ("\\.pkg\\'" . plsql-mode)
                      ("\\.pks\\'" . plsql-mode) ("\\.pkb\\'" . plsql-mode)
                      ("\\.sql\\'" . plsql-mode) ("\\.PLS\\'" . plsql-mode) 
                      ("\\.PKG\\'" . plsql-mode) ("\\.PKS\\'" . plsql-mode)
                      ("\\.PKB\\'" . plsql-mode) ("\\.SQL\\'" . plsql-mode)
                      ("\\.prc\\'" . plsql-mode) ("\\.fnc\\'" . plsql-mode)
                      ("\\.trg\\'" . plsql-mode) ("\\.vw\\'" . plsql-mode)
                      ("\\.PRC\\'" . plsql-mode) ("\\.FNC\\'" . plsql-mode)
                      ("\\.TRG\\'" . plsql-mode) ("\\.VW\\'" . plsql-mode))
                    auto-mode-alist ))


    #+end_src

*** Clojure

    I will be spending time this year learning clojure and making a terminal app in it here are some ext for it

    Much of this configuration is just lifted from the brave clojure book see

    https://github.com/flyingmachine/emacs-for-clojure/

    Rather than just using their code however I've added it into my own init.el.

    Note I have cloned their customizations directory.


    #+begin_src emacs-lisp

      ;; The packages you want installed. You can also install these
      ;; manually with M-x package-install
      ;; Add in your own as you wish:
      (defvar my-packages
        '(;; makes handling lisp expressions much, much easier
          ;; Cheatsheet: http://www.emacswiki.org/emacs/PareditCheatsheet
          paredit

          ;; key bindings and code colorization for Clojure
          ;; https://github.com/clojure-emacs/clojure-mode
          clojure-mode

          ;; extra syntax highlighting for clojure
          clojure-mode-extra-font-locking

          ;; integration with a Clojure REPL
          ;; https://github.com/clojure-emacs/cider
          cider

          ;; allow ido usage in as many contexts as possible. see
          ;; customizations/navigation.el line 23 for a description
          ;; of ido
          ;;ido-completing-read+

          ;; Enhances M-x to allow easier execution of commands. Provides
          ;; a filterable list of possible commands in the minibuffer
          ;; http://www.emacswiki.org/emacs/Smex
          smex

          ;; project navigation
          ;;projectile

          ;; colorful parenthesis matching
          rainbow-delimiters

          ;; edit html tags like sexps
          tagedit

          ;; git integration
          ;;magit
          ))

      ;; On OS X, an Emacs instance started from the graphical user
      ;; interface will have a different environment than a shell in a
      ;; terminal window, because OS X does not run a shell during the
      ;; login. Obviously this will lead to unexpected results when
      ;; calling external utilities like make from Emacs.
      ;; This library works around this problem by copying important
      ;; environment variables from the user's shell.
      ;; https://github.com/purcell/exec-path-from-shell
      (if (eq system-type 'darwin)
          (add-to-list 'my-packages 'exec-path-from-shell))

      (dolist (p my-packages)
        (when (not (package-installed-p p))
          (package-install p)))


      (add-to-list 'load-path "~/.emacs.d/customizations")


      ;;;;
      ;; Customization
      ;;;;

      ;; Add a directory to our load path so that when you `load` things
      ;; below, Emacs knows where to look for the corresponding file.
      ;; (add-to-list 'load-path "~/.emacs.d/customizations")

      ;; Sets up exec-path-from-shell so that Emacs will use the correct
      ;; environment variables
      (load "shell-integration.el")

      ;; These customizations make it easier for you to navigate files,
      ;; switch buffers, and choose options from the minibuffer.
      ;; These customizations change the way emacs looks and disable/enable
      ;; some user interface elements
      (load "ui.el")

      ;; These customizations make editing a bit nicer.
      (load "editing.el")

      ;; Hard-to-categorize customizations
      (load "misc.el")

      ;; For editing lisps
      (load "elisp-editing.el")

      ;; Langauage-specific
      (load "setup-clojure.el")
      (load "setup-js.el")
    #+end_src

*** Keyboard Changes

    Any simple keymap changes are here there can be more specific key binds per package which will be stored with their associated package.

    #+begin_src emacs-lisp
      (global-set-key (kbd "C-M-j") 'buffer-menu)

      (use-package evil
        :init
        (setq evil-want-integration t)
        (setq evil-want-keybinding nil)
        (setq evil-want-C-u-scroll t)
        (setq evil-want-C-i-jump nil)
        :config
        (evil-mode 1)
        (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
        (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)


        ;; Use visual line motions even outside of visual-line-mode buffers
        (evil-global-set-key 'motion "j" 'evil-next-visual-line)
        (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

        (evil-set-initial-state 'messages-buffer-mode 'normal)
        (evil-set-initial-state 'dashboard-mode 'normal)
        (evil-set-initial-state 'ibuffer-mode 'normal)
        (evil-set-initial-state 'bookmark-bmenu-mode 'normal)
        (evil-set-initial-state 'dired-mode 'emacs)
        (evil-set-initial-state 'sunrise-mode 'emacs))

      (use-package evil-collection
        :after evil
        :config
        (evil-collection-init))

    #+end_src

*** Cursors

    I am using the multiple cursor package. In emacs 28 I believe I can remove this but for now

    https://github.com/magnars/multiple-cursors.el
    
    M-x package-install multiple-cursors

    #+begin_src emacs-lisp
      (require 'multiple-cursors)
      (global-set-key (kbd "C-S-c C-S-c") 'mc/edit-lines)
      (global-set-key (kbd "C->") 'mc/mark-next-like-this)
      (global-set-key (kbd "C-<") 'mc/mark-previous-like-this)
      (global-set-key (kbd "C-c C-<") 'mc/mark-all-like-this)
    #+end_src 

*** Appearance

    I am using doom emacs bar as well as a theme from there for basic appearnance as well as some specific fonts. Please ensure you have IBM Plex Mono fonts installed if you want to use this.

    Please note I have some lines here commented in and out to account for different machines. I use emacs mostly in a Debian VM but I also use it on Macos and Windows natively for work. Font height and $PATH work different for macs.

    For all the icons fonts on windows you will need to "install" them. To do this follow the details 

    https://github.com/hlissner/doom-emacs/issues/2575

    The powershell commands are
     cd $tempFonts
     $destination = (New-Object -ComObject Shell.Application).Namespace(0x14)
     ls *.ttf | % { $destination.CopyHere($_.FullName, 0x10) }     
    

    #+begin_src emacs-lisp
      (global-hl-line-mode 1)       ; HL Lines globally on
      (set-face-background hl-line-face "gray22")
      ;; hidpi
      ;;(set-face-attribute 'default nil :font "IBM Plex Mono" :height 170)
      ;; normal screens
      (set-face-attribute 'default nil :font "IBM Plex Mono" :height 135)

      (use-package all-the-icons)

      (modus-themes-load-vivendi)

      (use-package rainbow-delimiters
        :hook (prog-mode . rainbow-delimiters-mode))

    #+end_src

**** Line Numbers

     We turn on line numbers but turn them off in various modes like terminal and dired.

    #+begin_src emacs-lisp
            (column-number-mode)
            (setq display-line-numbers-type 'relative)
            (global-display-line-numbers-mode t)

            ;; Disable line numbers for some modes
            (dolist (mode '(term-mode-hook
                            dired-mode-hook
                            shell-mode-hook
                            ;;org-mode-hook
                            eshell-mode-hook))
              (add-hook mode (lambda () (display-line-numbers-mode 0))))
    #+end_src


*** Python

    Here we set the python to python 3. My Mac has both python 2 and python 3 installed so this keeps it on the right one.

    
    #+begin_src emacs-lisp
      ;; python3 
      (setq python-shell-interpreter "python3")
    #+end_src

*** Mac Specific

    Here we use a package to force emacs to use the bash path on macos.

    #+begin_src emacs-lisp
      (use-package exec-path-from-shell)
      (when (memq window-system '(mac ns x))
	(exec-path-from-shell-initialize))
      (use-package command-log-mode)
    #+end_src

*** Treemacs

    While working on quick edits to projects I like treemacs for navigation. The tree like view lets me navigate a project I'm less familiar with easier than say dired. Everything here is basically set to defaults per notes available in the repo https://github.com/Alexander-Miller/treemacs.

    #+begin_src emacs-lisp
      (use-package treemacs
        :ensure t
        :defer t
        :init
        (with-eval-after-load 'winum
          (define-key winum-keymap (kbd "M-0") #'treemacs-select-window))
        :config
        (progn
          (setq treemacs-collapse-dirs                   (if treemacs-python-executable 3 0)
                treemacs-deferred-git-apply-delay        0.5
                treemacs-directory-name-transformer      #'identity
                treemacs-display-in-side-window          t
                treemacs-eldoc-display                   'simple
                treemacs-file-event-delay                5000
                treemacs-file-extension-regex            treemacs-last-period-regex-value
                treemacs-file-follow-delay               0.2
                treemacs-file-name-transformer           #'identity
                treemacs-follow-after-init               t
                treemacs-expand-after-init               t
                treemacs-find-workspace-method           'find-for-file-or-pick-first
                treemacs-git-command-pipe                ""
                treemacs-goto-tag-strategy               'refetch-index
                treemacs-indentation                     2
                treemacs-indentation-string              " "
                treemacs-is-never-other-window           nil
                treemacs-max-git-entries                 5000
                treemacs-missing-project-action          'ask
                treemacs-move-forward-on-expand          nil
                treemacs-no-png-images                   nil
                treemacs-no-delete-other-windows         t
                treemacs-project-follow-cleanup          nil
                treemacs-persist-file                    (expand-file-name ".cache/treemacs-persist" user-emacs-directory)
                treemacs-position                        'left
                treemacs-read-string-input               'from-child-frame
                treemacs-recenter-distance               0.1
                treemacs-recenter-after-file-follow      nil
                treemacs-recenter-after-tag-follow       nil
                treemacs-recenter-after-project-jump     'always
                treemacs-recenter-after-project-expand   'on-distance
                treemacs-litter-directories              '("/node_modules" "/.venv" "/.cask")
                treemacs-show-cursor                     nil
                treemacs-show-hidden-files               t
                treemacs-silent-filewatch                nil
                treemacs-silent-refresh                  nil
                treemacs-sorting                         'alphabetic-asc
                treemacs-select-when-already-in-treemacs 'move-back
                treemacs-space-between-root-nodes        t
                treemacs-tag-follow-cleanup              t
                treemacs-tag-follow-delay                1.5
                treemacs-text-scale                      nil
                treemacs-user-mode-line-format           nil
                treemacs-user-header-line-format         nil
                treemacs-wide-toggle-width               70
                treemacs-width                           35
                treemacs-width-increment                 1
                treemacs-width-is-initially-locked       t
                treemacs-workspace-switch-cleanup        nil)

          ;; The default width and height of the icons is 22 pixels. If you are
          ;; using a Hi-DPI display, uncomment this to double the icon size.
          ;;(treemacs-resize-icons 44)

          (treemacs-follow-mode t)
          (treemacs-filewatch-mode t)
          (treemacs-fringe-indicator-mode 'always)

          (pcase (cons (not (null (executable-find "git")))
                       (not (null treemacs-python-executable)))
            (`(t . t)
             (treemacs-git-mode 'deferred))
            (`(t . _)
             (treemacs-git-mode 'simple)))

          (treemacs-hide-gitignored-files-mode nil))
        :bind
        (:map global-map
              ("M-0"       . treemacs-select-window)
              ("C-x t 1"   . treemacs-delete-other-windows)
              ("C-x t t"   . treemacs)
              ("C-x t d"   . treemacs-select-directory)
              ("C-x t B"   . treemacs-bookmark)
              ("C-x t C-t" . treemacs-find-file)
              ("C-x t M-t" . treemacs-find-tag)))

      (use-package treemacs-evil
        :after (treemacs evil)
        :ensure t)

      (use-package treemacs-projectile
        :after (treemacs projectile)
        :ensure t)

      (use-package treemacs-icons-dired
        :hook (dired-mode . treemacs-icons-dired-enable-once)
        :ensure t)

      (use-package treemacs-magit
        :after (treemacs magit)
        :ensure t)

    #+end_src

*** Keycast mode

    I use keycast mode to help display what I am doing if I am pair programming. This is just set to C-c t k to turn it on and off showing in my doom modeline

    #+begin_src emacs-lisp 
      (use-package keycast
        :bind ("C-c t k" . +toggle-keycast)
        :config
        (define-minor-mode keycast-mode
          "Show current command and its key binding in the mode line (fix for use with doom-mode-line)."
          (defun +toggle-keycast()
            (interactive)
            (if (member '("" mode-line-keycast " ") global-mode-string)
                (progn (setq global-mode-string (delete '("" mode-line-keycast " ") global-mode-string))
                       (remove-hook 'pre-command-hook 'keycast--update)
                       (message "Keycast disabled"))
              (add-to-list 'global-mode-string '("" mode-line-keycast " "))
              (add-hook 'pre-command-hook 'keycast--update t)
              (message "Keycast enabled")))
          :global t
          (if keycast-mode
              (add-hook 'pre-command-hook 'keycast--update t)
            (remove-hook 'pre-command-hook 'keycast--update)))
        (add-to-list 'global-mode-string '("" mode-line-keycast))
      )
    #+end_src

*** Completion

    I enjoy using vertico for completion its simpler than company mode. I also have helpful enabled for extended help features because I am a novice with emacs. I also have YASNIPPET turned on with mostly default config.

    #+begin_src emacs-lisp 

      (use-package corfu
        :bind (:map corfu-map
                    ("C-j" . corfu-next)
                    ("C-k" . corfu-previous)
                    ("C-f" . corfu-insert))
        :custom
        (corfu-cycle t)
        :config
        (corfu-global-mode))


      (use-package vertico
        :bind (:map vertico-map
                    ("C-j" . vertico-next)
                    ("C-k" . vertico-previous)
                    ("C-f" . vertico-exit)
                    :map minibuffer-local-map
                    ("M-h" . dw/minibuffer-backward-kill))
        :custom
        (vertico-cycle t)
        :custom-face
        (vertico-current ((t (:background "#3a3f5a"))))
        :init
        (vertico-mode))


      (use-package orderless
        :init
        (setq completion-styles '(orderless)
              completion-category-defaults nil
              completion-category-overrides '((file (styles . (partial-completion))))))

      (use-package consult
        :demand t
        :bind (("C-s" . consult-line)
               ("C-M-l" . consult-imenu)
               ("C-M-j" . persp-switch-to-buffer*)
               :map minibuffer-local-map
               ("C-r" . consult-history))
        :custom
        (consult-project-root-function #'dw/get-project-root)
        (completion-in-region-function #'consult-completion-in-region))

      (use-package marginalia
        :after vertico
        :custom
        (marginalia-annotators '(marginalia-annotators-heavy marginalia-annotators-light nil))
        :init
        (marginalia-mode))

      (use-package helpful)

      (use-package yasnippet
        :ensure t
        :config
        (use-package yasnippet-snippets
          :ensure t)
        (yas-global-mode t)
        (add-to-list #'yas-snippet-dirs "my-personal-snippets")
        :diminish yas-minor-mode)

      (use-package which-key
        :init (which-key-mode)
        :diminish which-key-mode
        :config
        (setq which-key-idle-delay 1))

    #+end_src

*** LSP Mode

    For languages like python where the lsp is good we have lsp mode turned on. I don't care for this for lisps but the completions in python are good.

    #+begin_src emacs-lisp

      (defun efs/lsp-mode-setup ()
        (setq lsp-headerline-breadcrumb-segments '(path-up-to-project file symbols))
        (lsp-headerline-breadcrumb-mode))

      (use-package lsp-mode
        :commands (lsp lsp-deferred)
        :hook (lsp-mode . efs/lsp-mode-setup)
        :init
        (setq lsp-keymap-prefix "C-c l")  ;; Or 'C-l', 's-l'
        :config
        (lsp-enable-which-key-integration t))

    (use-package lsp-ui
        :hook (lsp-mode . lsp-ui-mode)
        :custom
        (lsp-ui-doc-position 'bottom))

      (use-package lsp-treemacs
        :after lsp)

    #+end_src

*** Everything Else

    Anything else random will be here. Right now this is just the git client which I have not configured fully for myself. This is sort of a "work in progress area" of my config.

#+begin_src emacs-lisp

  (global-set-key (kbd "C-x <C-return>") 'window-swap-states)

  (defun window-split-toggle ()
    "Toggle between horizontal and vertical split with two windows."
    (interactive)
    (if (> (length (window-list)) 2)
        (error "Can't toggle with more than 2 windows!")
      (let ((func (if (window-full-height-p)
                      #'split-window-vertically
                    #'split-window-horizontally)))
        (delete-other-windows)
        (funcall func)
        (save-selected-window
          (other-window 1)
          (switch-to-buffer (other-buffer))))))

  (use-package doom-modeline)
  (doom-modeline-mode)


#+end_src
