;;; svg-preview-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from svg-preview-mode.el

(autoload 'svg-preview-mode "svg-preview-mode" "\
Minor mode for live SVG previews.

By default previews update when the buffer changes.
See `svg-preview-preferred-frequency' if you wish to change this.

This is a minor mode.  If called interactively, toggle the
`Svg-Preview mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `svg-preview-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "svg-preview-mode" '("svg-preview-"))


;;; End of scraped data

(provide 'svg-preview-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; svg-preview-mode-autoloads.el ends here
